version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./server
    env_file: .env
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
    env_file: .env
    volumes:
      - ./client:/app
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: