version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: health_coach_db
      MYSQL_USER: healthuser
      MYSQL_PASSWORD: healthpass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./server
    environment:
      - DJANGO_SECRET_KEY=django-insecure-your-secret-key-here-change-in-production
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DB_NAME=health_coach_db
      - DB_USER=healthuser
      - DB_PASSWORD=healthpass
      - DB_HOST=db
      - DB_PORT=3306
      - OLLAMA_HOST=host.docker.internal
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: